baseurl = "/"
languageCode = "en-us"
title = "D2D Natural Resources and Data Literacy"
theme = "Blackburn"
author = "Oleksiy Anokhin"
# Shown in the side menu
copyright = "&copy; 2019. All rights reserved."
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    weight = 2
    pre = "<i class='fa fa-info-circle fa-fw'></i>"
    url = "/About/"
[[menu.main]]
    name = "Countries"
    weight = 5
    pre = "<i class='fa fa-building fa-fw'></i>"
    url = "/Countries/"
[[menu.main]]
    name = "Projects"
    weight = 6
    pre = "<i class='fa fa-folder-open fa-fw'></i>"
    url = "/Projects/"
[[menu.main]]
    name = "Team"
    weight = 9
    pre = "<i class='fa fa-user fa-fw'></i>"
    url = "/Team/"
[[menu.main]]
    name = "Photos"
    weight = 11
    pre = "<i class='fa fa-image fa-fw'></i>"
    url = "/Photos/"
[[menu.main]]
    name = "Donor"
    weight = 8
    pre = "<i class='fa fa-credit-card fa-fw'></i>"
    url = "https://www.bhp.com/community/bhp-foundation"
[[menu.main]]
    name = "Partners"
    weight = 7
    pre = "<i class='fa fa-laptop fa-fw'></i>"
    url = "/Partners/"
[[menu.main]]
    name = "GitHub"
    weight = 17
    pre = "<i class='fa fa-github fa-fw'></i>"
    url = "https://github.com/OleksiyAnokhin/d2d-data-literacy"
[[menu.main]]
    name = "Tools"
    weight = 15
    pre = "<i class='fa fa-wrench fa-fw'></i>"
    url = "/Tools/"
[[menu.main]]
    name = "Links"
    weight = 16
    pre = "<i class='fa fa-link fa-fw'></i>"
    url = "/Links/"
[[menu.main]]
    name = "Twitter"
    weight = 16
    pre = "<i class='fa fa-twitter fa-fw'></i>"
    url = "/twitter/"
[[menu.main]]
    name = "Contact Us"
    weight = 18
    pre = "<i class='fa fa-phone fa-fw'></i>"
    url = "/Contact/"
[[menu.main]]
    name = "Video"
    weight = 12
    pre = "<i class='fa fa-play-circle fa-fw'></i>"
    url = "/Video/"
[[menu.main]]
    name = "Media"
    weight = 10
    pre = "<i class='fa fa-envelope-open fa-fw'></i>"
    url = "/Media/"
[[menu.main]]
    name = "Data"
    weight = 13
    pre = "<i class='fa fa-database fa-fw'></i>"
    url = "/Data/"
[[menu.main]]
    name = "Presentations"
    weight = 14
    pre = "<i class='fa fa-clone fa-fw'></i>"
    url = "/Presentations/"
[[menu.main]]
name = "Home"
    weight = 1
    pre = "<i class='fa fa-home fa-fw'></i>"
    url = "/"
[[menu.main]]
name = "Posts"
    weight = 4
    pre = "<i class='fa fa-list fa-fw'></i>"
    url = "/post/"


[params]
    description = "Natural Resources and Data Literacy Program by D2D (IFC)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

