baseurl = "/"
languageCode = "en-us"
title = "D2D Natural Resources and Data Literacy"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/About/"
[[menu.main]]
    name = "Countries"
    url = "/countries/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Team"
    url = "/Team/"
[[menu.main]]
    name = "Photos"
    url = "/"
[[menu.main]]
    name = "Donor"
    url = "https://www.bhp.com/community/bhp-foundation"
[[menu.main]]
    name = "Partners"
    url = "/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/OleksiyAnokhin/d2d-data-literacy"
[[menu.main]]
    name = "Tools"
    url = "Tools"
[[menu.main]]
    name = "Links"
    url = "/"
[[menu.main]]
    name = "Twitter"
    url = "/"
[[menu.main]]
    name = "Contact Us"
    url = "/"


[params]
    description = "Natural Resources and Data Literacy Program by D2D (IFC)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

